### ISSUE TITLE
Feel reset - Star Gladiator

### ISSUE THREAD

**Issue by ZellGM** [xVaan/ROHispano#2]
**¿Su feature request está relacionada con un problema? Por favor describa.**
Tardo mucho tiempo en resetear los mapas con mi star gladiator [...]

**Describe la solución que te gustaría**
Aumentar el rate de dicho success 

**Describa alternativas que haya considerado**
Agregar esta función al VIP Membership, implementar el comando @feelreset o poner un npc que cobre por dicho proceso.

**Contexto adicional**
None

**Comment by xVaan** [comment]
Implementado.
